### ISSUE TITLE
vs2019 cant find NatSuite.ML.Vision namespace 

### ISSUE THREAD

**Issue by fingerx** [natsuite/NatML#4]
![image](https://user-images.githubusercontent.com/5524551/148002164-a77bba07-8493-4ad6-9467-a322b903c1a6.png)

**Comment by olokobayusuf** [comment]
Can you try regenerating the C# project from Unity? You should be able to do this from Unity's preferences menu. Do you get compiler errors in Unity? If not, I'll close this issue.

**Comment by fingerx** [comment]
using Unity2020.3.25f1 win64 il2cpp mode, build and run output exe is ok but in vs editor miss namespace, dont know why.

**Comment by fingerx** [comment]
maybe vs editor bug?

**Comment by olokobayusuf** [comment]
> maybe vs editor bug?

Probably. Thanks for closing.
