### ISSUE TITLE
Unity - Android make WebException : NameResolutionFailure

### ISSUE THREAD

**Issue by Youkwangchae** [natsuite/NatML#6]
![image](https://user-images.githubusercontent.com/64062195/150295012-7c2e8700-7081-4c58-bc92-0634cf4c066f.png)

Hi.
I tried movenet-3d mode samplel, but it makes WebException : NameResolutionFailure when request MLModeldata.
In Unity_Editor, this error isn't issued.

I think this exception means url link is inaccurate.

my Environment
: Unity 2019.4.28f1
Window 10, 64bit
Android 11 (API Level 30)

**Comment by olokobayusuf** [comment]
I've seen a report of this error before, and it has to do with your device's internet connection. Can you confirm that your app has internet permissions?

**Comment by Youkwangchae** [comment]
Thanks, olokobayusuf.
After confirm the Internet permission of app, This error doesn't report.

**Comment by olokobayusuf** [comment]
Sounds good!
